#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build qihoo_360t7 108mb ponly 24.10 hnat actions.

on:
  workflow_dispatch:
#   schedule:
#     - cron: '0 4 * * *'

env:
  # ponly 2410
  PONLY2410_REPO_URL: ${{ secrets.PONLY2410_REPO_URL }}
  PONLY2410_REPO_BRANCH: ${{ secrets.PONLY2410_REPO_BRANCH }}
  PONLY2410_REPO_PATCH: ${{ secrets.PONLY2410_REPO_PATCH }}
  # qihoo 360t7 108m
  Q360T7_PONLY2410_HOSTNAME: ${{ secrets.Q360T7_PONLY2410_HOSTNAME }}
  Q360T7_PONLY2410_PACKAGE: ${{ secrets.Q360T7_PONLY2410_PACKAGE }}
  Q360T7_PONLY2410_CONFIG: ${{ secrets.Q360T7_PONLY2410_CONFIG }}
  # feeds source
  ADD_FEED_SOURCE: ${{ secrets.ADD_FEED_SOURCE }}
  # diy script
  FIRMWARE_DIY_SCRIPT: ${{ secrets.FIRMWARE_DIY_SCRIPT }}
  # cmcc color theme
  ARGON_THEME_Q360: ${{ secrets.ARGON_THEME_Q360 }}
  # token
  ACCESS_SHA512SUM: ${{ secrets.ACCESS_SHA512SUM }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  # telegram bot
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  # upload options
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: false
  UPLOAD_WENSHUSHU: false  
  CACHE_TOOLCHAIN: true
  FIRMWARE_TAG: mt7981b
  SOURCE_CODE: padavanonly(237)
  DEVICE_NAME: Qihoo-360T7_108mb
  OUTPUT_FILENAME: padavanonly-2410-ryusan-mt7981b-qihoo_360t7-sysupgrade
  TZ: "Asia/Tokyo"

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
    - name: Checkout (チェックアウト)
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Free Disk Space (ハードドライブの空き容量を増やす)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Check Server Performance (サーバーのパフォーマンスを確認する)
      run: |
        echo "⚠️警告する⚠️"
        echo "割り当てられたサーバーのパフォーマンスには制限があります。プラグインを選択しすぎる場合は、CPU パフォーマンスに注意してください。"
        echo -e "既知のCPUモデル（降順）: 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "-------------------------CPU 情報---------------------------"
        echo "CPUの物理数  : $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUコア数    : $(nproc)"
        echo -e "CPUモデル情報:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "------------------------メモリ情報--------------------------"
        echo "メモリの詳細:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "---------------------ハードディスク情報---------------------"
        echo "ハードディスク容量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

#    - name: Combine Disks (ディスクを結合する)
#      uses: easimon/maximize-build-space@master
#      with:
#        swap-size-mb: 2048
#        temp-reserve-mb: 100
#        root-reserve-mb: 25600

    - name: Initialization environment (初期化環境)
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt -yqq update
        sudo -E apt -yqq full-upgrade
        sudo -E apt -yqq autoremove --purge
        sudo -E apt -yqq autoclean
        sudo -E apt -yqq clean
        sudo -E apt -yqq install zip rename dos2unix libfuse-dev
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E systemctl daemon-reload
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code (ソースコードのクローン)
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $PONLY2410_REPO_URL -b $PONLY2410_REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        ${{ secrets.ADD_FEED_SOURCE }}

        # Remove All China download sources (中国からのダウンロードソースを削除する)
        PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
        if [ -f "$PROJECT_MIRRORS_FILE" ]; then
          sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
        fi

    - name: Generate Variables (変数を生成する)
      run: |
        SOURCE_REPO="$(echo $PONLY2410_REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV

    - name: Cache Toolchain (キャッシュツールチェーン)
      if: env.CACHE_TOOLCHAIN == 'true'
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: false
        mixkey: ${{ env.SOURCE_REPO }}-${{ secrets.PONLY2410_REPO_BRANCH }}-${{ env.DEVICE_NAME }}
        prefix: ${{ github.workspace }}/openwrt

    - name: Updata & install feeds (アップデートとフィードのインストール)
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        rm -rf feeds/packages/lang/golang
        git clone https://github.com/sbwml/packages_lang_golang -b 24.x feeds/packages/lang/golang
        ./scripts/feeds install -a
        ./scripts/feeds install -a

    - name: Load custom configuration (カスタム構成を読み込む)
      run: |
        ${{ secrets.Q360T7_PONLY2410_CONFIG }}
        mv .config openwrt/.config
        cd openwrt
        ${{ secrets.PONLY2410_REPO_PATCH }}
        ${{ secrets.FIRMWARE_DIY_SCRIPT }}
        ${{ secrets.Q360T7_PONLY2410_HOSTNAME }}
        ${{ secrets.ARGON_THEME_Q360 }}

    - name: Download package (パッケージをダウンロード)
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware (ファームウェアをコンパイルする)
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: View Disk Usage (ディスク使用量の表示)
      if: (!cancelled())
      run: df -hT

    - name: Telegram notify when compilation error (コンパイルエラーが発生したときにテレグラムを使用して通知する)
      if: steps.compile.outputs.status != 'success' && !cancelled()
      env:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" -d text="*⛔コンパイルに失敗しました⛔*%0Aーーーーーーーーーーーーーーーーー%0A・🛜支援デバイス:%20${{ env.DEVICE_NAME }}%0A・📝ソースコード:%20${{ env.SOURCE_CODE }}%0A・📦リポジトリを:%20${{ env.SOURCE_REPO }}%0A・🔀ブランチ名前:%20${{ secrets.PONLY2410_REPO_BRANCH }}%0Aーーーーーーーーーーーーー" -d parse_mode="MarkdownV2"

    - name: Organize files (ファイルを整理する)
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        ls | grep -v *sysupgrade.bin | xargs rm -rdf
        mv *.bin temp.bin
        sha512sums -qq -r -P ${{ secrets.ACCESS_SHA512SUM }} sha512sums temp.bin
        ${{ secrets.Q360T7_PONLY2410_PACKAGE }}
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Firmware To Artifact (Artifactにアップロードする)
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true'
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.OUTPUT_FILENAME }}_${{ env.FILE_DATE }}
        path: ${{ env.FIRMWARE }}

    - name: Upload to Wenshushu and Telegram notification (コンパイルが成功したら、ウェンじさんにアップロードし、テレグラムを使用して通知します。)
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" -d text="*✅コンパイルが成功しました✅*%0Aーーーーーーーーーーーーーーーーー%0A・🛜支援デバイス:%20${{ env.DEVICE_NAME }}%0A・📝ソースコード:%20${{ env.SOURCE_CODE }}%0A・📦リポジトリを:%20${{ env.SOURCE_REPO }}%0A・🔀ブランチ名前:%20${{ secrets.PONLY2410_REPO_BRANCH }}%0A・📁ファイル名前:%20${{ env.OUTPUT_FILENAME}}_${{ env.FILE_DATE }}%0Aーーーーーーーーーーーーー" -d parse_mode="MarkdownV2"

    - name: Telegram notify when compilation complete (コンパイルが成功したらテレグラムを使用して通知する)
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_WENSHUSHU == 'false' && !cancelled()
      run: |
        curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" -d text="*✅コンパイルが成功しました✅*%0Aーーーーーーーーーーーーーーーーー%0A・🛜支援デバイス:%20${{ env.DEVICE_NAME }}%0A・📝ソースコード:%20${{ env.SOURCE_CODE }}%0A・📦リポジトリを:%20${{ env.SOURCE_REPO }}%0A・🔀ブランチ名前:%20${{ secrets.PONLY2410_REPO_BRANCH }}%0A・📁ファイル名前:%20${{ env.OUTPUT_FILENAME}}_${{ env.FILE_DATE }}%0Aーーーーーーーーーーーーー" -d parse_mode="MarkdownV2"

    - name: Generate Release Tag (タグを生成する)
      run: |
        RELEASE_TAG="$FIRMWARE_TAG-$DEVICE_NAME-$FILE_DATE"
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

    - name: Upload Firmware To Release (ファームウェアをアップロードする)
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_RELEASE == 'true'
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.FIRMWARE_TAG }}_${{ env.DEVICE_NAME }}_${{ env.FILE_DATE }}
        allowUpdates: false
        tag: ${{ env.RELEASE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}/*
        body: |
          **この${{ env.SOURCE_CODE }}ファームウェアはルータ${{ env.FIRMWARE_TAG }}専用です.**
          ### 📒 ${{ env.SOURCE_CODE }}の公式メインラインソースコードに基づいてコンパイルされたファームウェア.
          - これはCMCC-XR30の大きなパーティション✅eMMC Version✅専用ファームウェアです.
          - 🛜 支援デバイス: ${{ env.DEVICE_NAME }}
          - 📝 ソースコード: ${{ env.SOURCE_CODE }}
          - 📦 リポジトリを: ${{ env.SOURCE_REPO }}
          - 🔀 ブランチ名前: ${{ secrets.PONLY2410_REPO_BRANCH }}
          - 🌐 接続アドレス: 192.168.***.1 または padavanonly.lan
          - 🔑 パスワードは: なし
          ### ⚠️ 警告する ⚠️
          - ‼️現在のリポジトリによってコンパイルされたファームウェアはすべて非公開でカスタマイズされています。
          - ⛔️強制フラッシュ⛔️によってデバイスが損傷した場合、このリポジトリはデバイスの損傷について一切責任を負いません。

    - name: Delete old workflow runs (古いワークフロー実行を削除する)
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 3

    - name: Delete Old Releases (古いリリースを削除する)
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 15
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
