#
# Copyright (c) 2019-2020 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
#

name: Build cudy tr3000-v1 512mb ponly 24.10 kernel 6.6 actions.

on:
  workflow_dispatch:
    inputs:
      restore_configuration:
        description: 'Restore configuration archive (バックアップした構成アーカイブを復元する)'
        type: boolean
        default: false
      telegram_notify:
        description: 'Enable Telegram Notify (テレグラム通知を有効にする)'
        type: boolean
        default: false
      upload_firmware:
        description: 'Upload Firmware To Artifact (アーティファクトにアップロードする)'
        type: boolean
        default: false
      upload_release:
        description: 'Upload Firmware To Release (リリースをアップロードする)'
        type: boolean
        default: false
      upload_wenshushu:
        description: 'Upload Firmware To WENSHUSHU (ウェンおじさんにアップロードする)'
        type: boolean
        default: false
  schedule:
    - cron: '0 19 * * 0'

env:
  # immortalwrt 2410
  PONLY2410_REPO_URL: ${{ secrets.PONLY2410_REPO_URL }}
  PONLY2410_K66_REPO_BRANCH: ${{ secrets.PONLY2410_K66_REPO_BRANCH }}
  PONLY2410_REPO_PATCH: ${{ secrets.PONLY2410_REPO_PATCH }}
  # cudy tr3000 v1 modded spi nand 256m
  CD_TR3000_512MB_PONLY2410_K66_HOSTNAME: ${{ secrets.CD_TR3000_512MB_PONLY2410_K66_HOSTNAME }}
  CD_TR3000_512MB_PONLY2410_K66_CONFIG: ${{ secrets.CD_TR3000_512MB_PONLY2410_K66_CONFIG }}
  CD_TR3000_256M_PONLY2410_K66_BACKUP: ${{ secrets.CD_TR3000_256M_PONLY2410_K66_BACKUP }}
  # feeds source
  ADD_FEED_SOURCE: ${{ secrets.ADD_FEED_SOURCE }}
  # diy script
  FIRMWARE_DIY_SCRIPT: ${{ secrets.FIRMWARE_DIY_SCRIPT }}
  # netcore color theme
  ARGON_THEME_CUDY: ${{ secrets.ARGON_THEME_CUDY }}
  # token
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_SHA512SUM: ${{ secrets.ACCESS_SHA512SUM }}
  ACCESS_REPACKAGE_SHA512: ${{ secrets.ACCESS_REPACKAGE_SHA512 }}
  # telegram bot
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  # hardware & repo info
  DEVICE_NAME: Cudy-TR3000_v1
  CPU_TAG: mt7981b
  FLASH_TAG: SPI_NAND_512MB
  SOURCE_CODE: padavanonly(237)
  KERNEL_VERSION: kernel_6.6
  OUTPUT_FILENAME: padavanonly-24.10-ryu-mt7981b-cudy_tr3000-v1-512mb-kernel6.6-sysupgrade
  TZ: "Asia/Tokyo"

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
#    - name: This job runs on schedule or if inputs.should_run is true (このジョブはスケジュールどおりに実行されるか、inputs.should_runがtrueの場合に実行されます)
#      uses: ./.github/workflows/build_cudy_tr3000-v1_512m_ponly_2410_k66.yml
#      with:
#        restore_configuration: ${{ !contains(inputs.restore_configuration, 'false') }}
#        upload_release: ${{ !contains(inputs.upload_release, 'false') }}
#        upload_wenshushu: ${{ !contains(inputs.upload_wenshushu, 'false') }}

    - name: Checkout (チェックアウト)
      uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Free Disk Space (ハードドライブの空き容量を増やす)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Check Server Performance (サーバーのパフォーマンスを確認する)
      run: |
        echo "⚠️警告する⚠️"
        echo "割り当てられたサーバーのパフォーマンスには制限があります。プラグインを選択しすぎる場合は、CPU パフォーマンスに注意してください。"
        echo -e "既知のCPUモデル（降順）: 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "-------------------------CPU 情報---------------------------"
        echo "CPUの物理数  : $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPUコア数    : $(nproc)"
        echo -e "CPUモデル情報:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "------------------------メモリ情報--------------------------"
        echo "メモリの詳細:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "---------------------ハードディスク情報---------------------"
        echo "ハードディスク容量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Initialization environment (初期化環境)
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt -yqq update
        sudo -E apt -yqq full-upgrade
        sudo -E apt -yqq autoremove --purge
        sudo -E apt -yqq autoclean
        sudo -E apt -yqq clean
        sudo -E apt -yqq install zip rename dos2unix libfuse-dev
        sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.org/init_build_environment.sh)'
        sudo -E systemctl daemon-reload
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code (ソースコードのクローン)
      working-directory: /workdir
      run: |
        df -hT $PWD
        git clone $PONLY2410_REPO_URL -b $PONLY2410_K66_REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        cd openwrt
        ${{ secrets.ADD_FEED_SOURCE }}

        # Remove All China download sources (中国からのダウンロードソースを削除する)
        PROJECT_MIRRORS_FILE="./scripts/projectsmirrors.json"
        if [ -f "$PROJECT_MIRRORS_FILE" ]; then
          sed -i '/.cn\//d; /tencent/d; /aliyun/d' "$PROJECT_MIRRORS_FILE"
        fi

    - name: Generate Variables (変数を生成する)
      run: |
        SOURCE_REPO="$(echo $PONLY2410_REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV

    - name: Cache Toolchain (キャッシュツールチェーン)
      uses: HiGarfield/cachewrtbuild@main
      with:
        ccache: true
        mixkey: MT7981b-${{ env.SOURCE_CODE }}-${{ env.SOURCE_REPO }}-${{ secrets.PONLY2410_K66_REPO_BRANCH }}
        prefix: ${{ github.workspace }}/openwrt

    - name: Updata & install feeds (アップデートとフィードのインストール)
      working-directory: ./openwrt
      run: |
        ./scripts/feeds update -a
        rm -rf feeds/packages/lang/golang
        git clone https://github.com/sbwml/packages_lang_golang -b 25.x feeds/packages/lang/golang
        ./scripts/feeds install -a
        ./scripts/feeds install -a

    - name: Load custom configuration (カスタム構成を読み込む)
      run: |
        ${{ secrets.CD_TR3000_512MB_PONLY2410_K66_CONFIG }}
        cat >> .config <<-"EOF"
        CONFIG_DOCKER_CGROUP_OPTIONS=y
        CONFIG_DOCKER_NET_MACVLAN=y
        CONFIG_DOCKER_STO_EXT4=y
        CONFIG_PACKAGE_docker=y
        CONFIG_PACKAGE_docker-compose=y
        CONFIG_PACKAGE_dockerd=y
        CONFIG_PACKAGE_luci-app-dockerman=y
        CONFIG_PACKAGE_luci-i18n-dockerman-zh-cn=y
        CONFIG_PACKAGE_luci-lib-docker=y
        EOF
        mv .config openwrt/.config
        cd openwrt
        ${{ secrets.PONLY2410_REPO_PATCH }}
        ${{ secrets.FIRMWARE_DIY_SCRIPT }}
        ${{ secrets.CD_TR3000_512MB_PONLY2410_K66_HOSTNAME }}
        ${{ secrets.ARGON_THEME_CUDY }}

    - name: Restore configuration archive (バックアップした構成アーカイブを復元する)
      if: (github.event.inputs.restore_configuration == 'true' && github.event.inputs.restore_configuration != 'false') || contains(github.event.action, 'restore_configuration') && !cancelled()
      working-directory: ./openwrt
      run: |
        ${{ secrets.CD_TR3000_256M_PONLY2410_K66_BACKUP }}

    - name: Download package (パッケージをダウンロード)
      id: package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware (ファームウェアをコンパイルする)
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Upgrading variables (変数のアップグレード)
      run: |
        echo "OUTPUT_FILENAME=${OUTPUT_FILENAME}_${FILE_DATE}" >> $GITHUB_ENV

    - name: View Disk Usage (ディスク使用量の表示)
      if: (!cancelled())
      run: df -hT

    - name: Telegram notify when compilation error (コンパイルエラーが発生したときにテレグラムを使用して通知する)
      if: steps.compile.outputs.status != 'success' && (github.event.inputs.telegram_notify == 'true' && github.event.inputs.telegram_notify != 'false') || contains(github.event.action, 'telegram_notify') && !cancelled()
      env:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      run: |
        curl -s -o /dev/null -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=❌%20コンパイルに失敗しました！%20❌%0A%0A＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝%0A・🛜支援デバイス:%0A　%20　${{ env.DEVICE_NAME }}%0Aーーーーーーーーーーーーーーーーー%0A・💽フラッシュは:%0A　%20　${{ env.FLASH_TAG }}%0Aーーーーーーーーーーーーーーーーー%0A・🧿カーネル使用:%0A　%20　${{ env.KERNEL_VERSION }}%0Aーーーーーーーーーーーーーーーーー%0A・📝ソースコード:%0A　%20　${{ env.SOURCE_CODE }}%0Aーーーーーーーーーーーーーーーーー%0A・📦リポジトリを:%0A　%20　${{ env.SOURCE_REPO }}%0Aーーーーーーーーーーーーーーーーー%0A・🔀ブランチ名前:%0A　%20　${{ secrets.PONLY2410_K66_REPO_BRANCH }}%0Aーーーーーーーーーーーーーーーーー%0A・❌エラーの時間:%0A　%20　$(date +'%Y年%m月%d日_%H時%M分')%0A＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝%0A"

    - name: Organize files (ファイルを整理する)
      id: organize
      if: steps.compile.outputs.status == 'success' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        ls
        ls | grep -v *sysupgrade.bin | xargs rm -rdf
        mv *.bin ${{ env.OUTPUT_FILENAME }}.bin
        sha512sums -qq -r -P ${{ secrets.ACCESS_SHA512SUM }} sha512sums ${{ env.OUTPUT_FILENAME }}.bin
        ${{ secrets.ACCESS_REPACKAGE_SHA512 }} ${{ env.OUTPUT_FILENAME }}.bin
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "status=success" >> $GITHUB_OUTPUT

    - name: Upload Firmware To Artifact (Artifactにアップロードする)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_firmware == 'true' && github.event.inputs.upload_firmware  != 'false') || contains(github.event.action, 'upload_firmware') && !cancelled()
      uses: actions/upload-artifact@main
      with:
        name: ${{ env.OUTPUT_FILENAME }}
        path: ${{ env.FIRMWARE }}

    - name: Telegram notify when compilation complete (コンパイルが成功したらテレグラムを使用して通知する)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.telegram_notify == 'true' && github.event.inputs.telegram_notify != 'false') || contains(github.event.action, 'telegram_notify') && !cancelled() 
      run: |
        curl -s -o /dev/null -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=✅%20コンパイルが成功しました！%20✅%0A%0A＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝%0A・🛜支援デバイス:%0A　%20　${{ env.DEVICE_NAME }}%0Aーーーーーーーーーーーーーーーーー%0A・💽フラッシュは:%0A　%20　${{ env.FLASH_TAG }}%0Aーーーーーーーーーーーーーーーーー%0A・🧿カーネル使用:%0A　%20　${{ env.KERNEL_VERSION }}%0Aーーーーーーーーーーーーーーーーー%0A・📝ソースコード:%0A　%20　${{ env.SOURCE_CODE }}%0Aーーーーーーーーーーーーーーーーー%0A・📦リポジトリを:%0A　%20　${{ env.SOURCE_REPO }}%0Aーーーーーーーーーーーーーーーーー%0A・🔀ブランチ名前:%0A　%20　${{ secrets.PONLY2410_K66_REPO_BRANCH }}%0Aーーーーーーーーーーーーーーーーー%0A・📁ファイル名前:%0A　%20　${{ env.OUTPUT_FILENAME}}%0A＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝%0A"

    - name: Upload to wenshushu (ウェンおじさんにアップロードする)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_wenshushu == 'true' && github.event.inputs.upload_wenshushu != 'false') || contains(github.event.action, 'upload_wenshushu') && !cancelled()
      working-directory: ./openwrt
      run: |
        curl -fsSL git.io/file-transfer | sh
        ./transfer wss -s -p 16 -t 600 --no-progress ${FIRMWARE} 2>&1 | tee wenshushu.log
        WENSHUSHU=$(cat wenshushu.log | grep 'Manage Link:' | cut -d' ' -f3-)
        echo "WENSHUSHU=$WENSHUSHU" >> $GITHUB_ENV

    - name: Telegram notify when compilation complete and upload to wenshushu (コンパイルが成功したらテレグラムを使用して通知し、ウェンおじさんにアップロードする)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_wenshushu == 'true' && github.event.inputs.upload_wenshushu != 'false') || contains(github.event.action, 'upload_wenshushu') && !cancelled()
      working-directory: ./openwrt
      run: |
        curl -s -o /dev/null -X GET "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage?chat_id=${{ secrets.TELEGRAM_CHAT_ID }}&text=✅%20コンパイルが成功しました！%20✅%0A%0A＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝%0A・🛜支援デバイス:%0A　%20　${{ env.DEVICE_NAME }}%0Aーーーーーーーーーーーーーーーー%0A・💽フラッシュは:%0A　%20　${{ env.FLASH_TAG }}%0Aーーーーーーーーーーーーーーーー%0A・🧿カーネル使用:%0A　%20　${{ env.KERNEL_VERSION }}%0Aーーーーーーーーーーーーーーーーー%0A・📝ソースコード:%0A　%20　${{ env.SOURCE_CODE }}%0Aーーーーーーーーーーーーーーーー%0A・📦リポジトリを:%0A　%20　${{ env.SOURCE_REPO }}%0Aーーーーーーーーーーーーーーーー%0A・🔀ブランチ名前:%0A　%20　${{ secrets.PONLY2410_K66_REPO_BRANCH }}%0Aーーーーーーーーーーーーーーーー%0A・📁ファイル名前:%0A　%20　${{ env.OUTPUT_FILENAME}}%0Aーーーーーーーーーーーーーーーー%0A・👲🏻ウェンじさん:%0A　%20　${{ env.WENSHUSHU }}%0A＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝%0A"

    - name: Generate Release Tag (タグを生成する)
      run: |
        RELEASE_TAG="$CPU_TAG-$DEVICE_NAME-$FLASH_TAG-$KERNEL_VERSION-$FILE_DATE"
        echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

    - name: Upload Firmware To Release (アーティファクトをアップロードする)
      if: steps.compile.outputs.status == 'success' && steps.organize.outputs.status == 'success' && (github.event.inputs.upload_release == 'true' && github.event.inputs.upload_release  != 'false') || contains(github.event.action, 'upload_release') && !cancelled()
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.CPU_TAG }}_${{ env.DEVICE_NAME }}_${{ env.FLASH_TAG }}_${{ env.KERNEL_VERSION }}_${{ env.FILE_DATE }}
        allowUpdates: false
        tag: ${{ env.RELEASE_TAG }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: ${{ env.FIRMWARE }}/*
        body: |
          **このファームウェアは、CPU「${{ env.CPU_TAG }}」モデル「${{ env.DEVICE_NAME }}」を搭載したルーター✅ ${{ env.FLASH_TAG }} ✅にのみ適しています。**
          ### 📒「${{ env.SOURCE_CODE }}」リポジトリのソースコードからコンパイルされたファームウェア。
          - 🛜 支援デバイス: ${{ env.DEVICE_NAME }}
          - 💽 フラッシュは: ${{ env.FLASH_TAG }}
          - 🧿 カーネル使用: ${{ env.KERNEL_VERSION }}
          - 📝 ソースコード: ${{ env.SOURCE_CODE }}
          - 📦 リポジトリを: ${{ env.SOURCE_REPO }}
          - 🔀 ブランチ名前: ${{ secrets.PONLY2410_K66_REPO_BRANCH }}
          - 🌐 接続アドレス: 192.168.6.1
          - 🔑 パスワードは: なし
          ### ⚠️ 警告する ⚠️
          - ‼️現在のリポジトリによってコンパイルされたファームウェアはすべて非公開でカスタマイズされています。
          - ⛔️強制フラッシュ⛔️によってデバイスが損傷した場合、このリポジトリはデバイスの損傷について一切責任を負いません。

    - name: Delete old workflow runs (古いワークフロー実行を削除する)
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 7
        keep_minimum_runs: 4

    - name: Delete Old Releases (古いリリースを削除する)
      uses: dev-drprasad/delete-older-releases@master
      with:
        keep_latest: 8
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  
